apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: tools
    name: tools
  name: tools
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tools
  template:
    metadata:
      labels:
        app: tools
        name: tools
    spec:
      containers:
      - env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: OLLAMA_ENDPOINT
          value: http://ollama.ollama.svc.cluster.local:11434/api
        image: ghcr.io/kainlite/tools:eb690f1b4e031a1d5b48a8e09047d9013ae1e95b
        imagePullPolicy: Always
        name: tools
        ports:
        - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: regcred
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
